name: security

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --all-groups --frozen
      - run: uv run --frozen bandit -c bandit.yaml -r src
      - run: uv run --frozen pip-audit --skip-editable
